version: "3.1"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: tester
      MYSQL_PASSWORD: testerpass
      MYSQL_ROOT_PASSWORD: rootpass
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data:/var/lib/mysql