version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - ./.env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  redis:
    image: redis:alpine
    container_name: redis-server
  celery:
    restart: always
    container_name: celery-worker
    build:
      context: .
    command: celery -A composeexample worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web