version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - type: bind
        source: .
        target: /code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"